version: 0.0
os: linux
files:
  - source: /
    destination: ~/../home/ec2-user/project
    file_exists_behavior: OVERWRITE
permissions:
  - object: /
    owner: root
    group: root
    mode: 777
hooks:
  ApplicationStop:
  - location: ~/../home/ec2-user/project/scripts/stop_server.sh
    timeout: 300
    runas: root
  ApplicationStart:
    - location: ~/../home/ec2-user/project/scripts/start_server.sh
      timeout: 300
      runas: root