version: '3.3'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INIT_ROOT_USERNAME=root
      - MONGO_INIT_ROOT_PASSWORD=password
    ports: 
      - 27017:27017
    networks:
      - my_network

  backend:
    image: public.ecr.aws/s0z9h6z8/my_todo_backend:latest
    container_name: backend
    ports: 
      - 8000:8000
    depends_on:
      - mongodb
    networks:
      - my_network
    
  frontend:
    image: public.ecr.aws/s0z9h6z8/my_todo_backend:latest
    container_name: react
    ports: 
      - 3000:3000
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network: