version: '3.3'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INIT_ROOT_USERNAME=root
      - MONGO_INIT_ROOT_PASSWORD=password
    ports: 
      - 27017:27017
    networks:
      - my_network

  backend:
    build: backend
    image: backend
    container_name: backend
    ports: 
      - 8000:8000
    depends_on:
      - mongodb
    networks:
      - my_network
    
  frontend:
    build: frontend
    image: frontend
    container_name: react
    ports: 
      - 3000:3000
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network: